[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = [
  "pip install -r App/Back(Django)/requirementsProd.txt"

[phases.build]
cmds = [
  "python3 App/Back(Django)/manage.py collectstatic --noinput"
]

[start]
cmd = "gunicorn backend.wsgi:application --chdir App/Back(Django) --bind 0.0.0.0:${PORT}"
