[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = [
  "pip install -r App/back_django/linuxRequirements.txt"
]

[phases.build]
cmds = [
  "python3 App/back_django/manage.py collectstatic --noinput"
]

[start]
cmd = "gunicorn backend.wsgi:application --chdir App/back_django --bind 0.0.0.0:${PORT}"
