[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "postgresql"]

[phases.install]
cmds = [
  "python3 -m pip install -r 'App/Back(Django)/requirements.txt'"
]

[phases.build]
cmds = [
  'python3 App/Back(Django)/manage.py collectstatic --noinput'
]

[start]
cmd = 'gunicorn backend.wsgi:application --chdir App/Back(Django) --bind 0.0.0.0:${PORT}'
